version: "3"
services:
  app:
    image: errbot-slack
    container_name: errbot
    build:
      context: .
    restart: always
    env_file:
      - ../env_file/errbot.env 
    dns:
      - 8.8.8.8
      - 8.8.4.4
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    volumes:
      - '~/container_errbot:/home/errbotuser/chatops/host_vol'
    user: "1000:1000"
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}.{{.ID}}"
